### ISSUE TITLE
Using devenv.sh to work on Django itself

### ISSUE THREAD

**Issue by joshuadavidthomas** [joshuadavidthomas/joshthomas.dev#276]
1. Install devenv.sh
2. Add the following to `.git/info/exclude`:
   
   ```
   # Devenv
   .devenv*
   devenv*

   # direnv
   .direnv
   .envrc

   # pre-commit
   .pre-commit-config.yaml
   ```
3. Run `git config advice.addIgnoredFile false` command to make sure `devenv.lock` is not added to Git. (devenv.sh automatically tries to add/stage it)
4. Run `devenv init` in base of Django fork
5. Adjust `devenv.nix` to the following:

   ```nix
   { pkgs, ... }:

   {
     languages.python = {
       enable = true;
       version = "3.10";
       venv.enable = true;
     };

     scripts.runtests.exec = ''
       ./tests/runtests.py
     '';

     enterShell = ''
       python -m pip install --upgrade pip
       python -m pip install -e .
       python -m pip install -r ./tests/requirements/py3.txt
     '';
   }
   ```
6. Adjust `devenv.yaml` to the following:

   ```yaml
   inputs:
     nixpkgs:
       url: github:NixOS/nixpkgs/nixpkgs-unstable
     nixpkgs-python:
       url: github:cachix/nixpkgs-python
   ```
